export const SHOW_TIME_RESPONSE={

    GET_SHOW_TIME_BY_ID:'SHOW_TIME FATCH  SUCCESSFULLY',
    ERROR_SHOW_TIME_BY_ID:'ERROR RETRIEVING SHOW_TIME ',
    ADD_SHOW_TIME:'ADD SHOW_TIME SUCCESSFULLY',
    ERROR_ADD_SHOW_TIME:'ERROR TO ADD SHOW_TIME',
    UPDATE_SHOW_TIME:'SHOW_TIME UPDATE SUCCESSFULLY',
    ERROR_UPDATE_SHOW_TIME:'ERROR TO UPDATE SHOW_TIME',
    DELETE_SHOW_TIME:'SHOW_TIME DELETE SUCCESSFULLY',
    ERROR_DELETE_SHOW_TIME:'ERROR TO DELETE SHOW_TIME',
    SHOW_TIME_NOT_FOUND:'SHOW_TIME NOT FOUND',
    GET_MOVIE_THEATER:'MOVIE AND THEATER FATCH SUCCESSFULLY',
    ERROR_GET_MOVIE_THEATER:'ERROR TO FATCH MOVIE AND THEATER'
}